name: tiangou
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^2.14.0
  crypto: ^3.0.3
  http: ^1.2.1
  taggy: ^0.1.2+3
  isar: ^3.1.0+1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11
  analyzer: ^5.13.0